name: minerl
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip
  - cudatoolkit=10.2
  - pytorch
  - torchvision>=0.4
  - pip:
    - argparse
    - crowdai_api
    - coloredlogs
    - gym==0.19.0
    - imageio
    - flatten-dict
    - hydra-core
    - ipdb
    - matplotlib
    - minerl
    - moviepy
    - numpy
    - opencv-python
    - pyro4
    - pytest
    - pyvirtualdisplay
    - wandb
