name: minerl
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.2
  - pytorch
  - torchvision>=0.4
  - pip:
    - crowdai_api
    - minerl
    - coloredlogs
    - matplotlib
    - pyro4
    - ipdb
    - wandb
    - argparse
    - numpy
    - opencv-python
    - gym==0.19.0
    - pyvirtualdisplay
    - hydra-core
