
algorithm: 'curiosity_pretraining'
checkpoint_frequency: 500

env: ${..env}
n_observation_frames: 3
alpha: 1e-1
wandb: ???

starting_steps: 0
curiosity_pretraining_steps: 2000
suppress_snowball_steps: 3000  # this should be larger than the curiosity pretraining
training_steps: 20000

batch_size: 256
discount_factor: 0.99
curiosity_lr: 1e-3
q_lr: 3e-4
policy_lr: 1e-4
tau: .05
double_q: false


seed: 0
