name: 'bc'
algorithm: 'supervised_learning'
loss_function: 'bc'
drq: false

expert_dataset: true
online: false

epochs: 20
batch_size: 128
max_training_steps: 1000000

learning_rate: .001

entropy_tuning: false
