name: 'iqlearn_offline'
algorithm: 'supervised_learning'
loss_function: 'iqlearn'
loss: 'value_expert'
drq: true
expert_done_value: 1

online: false
expert_dataset: true

epochs: 20
batch_size: 64
max_training_steps: 1000000

learning_rate: 3e-4
discount_factor: 0.99

alpha: 1e-1
entropy_tuning: false
decay_alpha: false
final_alpha: 1e-2
