name: 'iqlearn_online'
algorithm: 'online_imitation'  # curiosity, supervised_learning, online_imitation, sac
loss_function: 'iqlearn'
loss: 'value'
drq: true

expert_dataset: true
expert_sample_fraction: 0.5
batch_size: 32


starting_steps: 10000
suppress_snowball_steps: 500

learning_rate: 3e-4
discount_factor: 0.99
