name: 'iqlearn_offline'
algorithm: 'offline_imitation'  # curiosity, supervised_learning, online_imitation, sac
loss_function: 'iqlearn'
loss: 'value'

expert_dataset: true
batch_size: 64


starting_steps: 2000
suppress_snowball_steps: 500
training_steps: 10000

learning_rate: 3e-4
discount_factor: 0.99
