name: 'iqlearn_sac'
algorithm: 'curious_IQ'
loss_function: 'iqlearn'
loss: 'value'
drq: true
target_q: true  # for iqlearn q function
normalize_reward: false  # for curiosity rewards


starting_steps: 5000
suppress_snowball_steps: 2000
training_steps: 30000

curiosity_pretraining_steps: 0  # training on the random data
curiosity_only_steps: 0
curiosity_fade_out_steps: 0

batch_size: 256
expert_sample_fraction: 0.5

discount_factor: 0.99
curiosity_lr: 0
q_lr: 0
iqlearn_lr: 3e-5
policy_lr: 1e-4

tau: .005

expert_dataset: true
double_q: false
