name: 'iqlearn_sac'
algorithm: 'sac'
loss_function: 'iqlearn'
loss: 'value'
drq: true
expert_done_value: 1
policy_done_value: 0

online: true
expert_dataset: true
expert_sample_fraction: 0.5
batch_size: 32


discount_factor: 0.99
q_lr: 3e-4
policy_lr: 1e-4

updates_per_step: 1
target_update_interval: 1
target_q: true  # for iqlearn q function
tau: .05
double_q: false  # not implemented

alpha: 1e-1
decay_alpha: false
final_alpha: 1e-2
entropy_tuning: true
match_expert_entropy: true
target_entropy_ratio: 0.2  # otherwise
entropy_lr: 3e-5


starting_steps: 1000
training_steps: 50000
