name: 'iqlearn_online'
algorithm: 'online_imitation'  # curiosity, supervised_learning, online_imitation, sac
loss_function: 'iqlearn'
loss: 'value'
drq: false

expert_dataset: true
expert_sample_fraction: 0.5
batch_size: 128


starting_steps: 2000
suppress_snowball_steps: 500
training_steps: 10000

learning_rate: 3e-4
discount_factor: 0.99
