name: 'iqlearn_sac'
algorithm: 'sac'
loss_function: 'iqlearn'
loss: 'value'

expert_dataset: true

starting_steps: 2000
suppress_snowball_steps: 500
training_steps: 10000

batch_size: 256
discount_factor: 0.99
q_lr: 3e-4
policy_lr: 1e-4

tau: .05
double_q: false
