name: 'iqlearn_sac'
algorithm: 'sac'
loss_function: 'iqlearn'
loss: 'value'
drq: true

expert_dataset: true
expert_sample_fraction: 0.5
batch_size: 32

discount_factor: 0.99
q_lr: 3e-4
policy_lr: 1e-4

target_q: true  # for iqlearn q function
tau: .05

entropy_adjustment: false
target_entropy_ratio: 0.05
entropy_lr: 1e-4


starting_steps: 1000
suppress_snowball_steps: 2000
training_steps: 50000
