defaults:
  - method: iqlearn_online
  - env: cave
  - pretraining: curiosity
  - _self_

exp_name: ''
project_name: ${env.name}
device: ???  # to be specified later
pretrain: ???
env: ???
method: ???
wandb: ???

# model attributes
cnn_layers: 17  # max is 17
n_observation_frames: 6  # includes current pov
alpha: 1e-2

# data augmentation
inventory_noise: 0.1  # scale of gaussian noise added to inventory
random_translate: true
mirror_augment: true


seed: 0
checkpoint_frequency: 1000
hydra_base_dir: ""
