defaults:
  - method: iqlearn_online
  - env: cave
  - pretraining: none
  - _self_

exp_name: ''
project_name: ${env.name}
device: ???  # to be specified later
env: ???
method: ???
wandb: ???

# training params
cyclic_learning_rate: true

# model attributes
cnn_layers: 12  # max is 17
linear_layer_size: 512
n_observation_frames: 3  # includes current frame
alpha: 1e-1

# lstm
# set layers and hidden size to 0 to disable
lstm_layers: 1
lstm_hidden_size: 512
lstm_segment_length: 10

# data augmentation
normalize_obs: true
inventory_noise: 0.1  # scale of gaussian noise added to inventory
random_translate: true
mirror_augment: false # leave off

# curriculum learning
curriculum_training: true
curriculum_fraction_of_training: 0.6
initial_curriculum_size: 100
curriculum_refresh_steps: 2000
variable_training_episode_length: true
min_training_episode_length: 500
emphasize_new_samples: true
emphasized_fraction: 0.15
emphasis_relative_sample_frequency: 3
extracurricular_sparsity: 100

# record keeping
seed: 0
checkpoint_frequency: 5000
eval_frequency: 0 # only calculates reward, doesn't save video
eval_episodes: 5
start_time: ???
hydra_base_dir: ""
