defaults:
  - method: iqlearn_online
  - env: cave
  - pretraining: curiosity
  - _self_

exp_name: ''
project_name: ${env.name}
device: ???  # to be specified later
pretrain: ???
env: ???
method: ???
wandb: ???


cnn_layers: 17
n_observation_frames: 3
frame_selection_noise: 0

alpha: 1e-2


seed: 0
checkpoint_frequency: 1000
hydra_base_dir: ""
