defaults:
  - context: minerl
  - env: cave
  - method: iqlearn_online
  - model: lstm
  - dataset: curriculum
  - _self_

exp_name: ''
project_name: ${env.name}
device: ???  # to be specified later
env: ???
method: ???
wandb: ???

# general training params
cyclic_learning_rate: true
training_timeout:  86400 # 24 hours

# record keeping
seed: 0
checkpoint_frequency: 5000  # save model
save_gifs: true  # save gifs to wandb at checkpoints
eval_frequency: 0  # calc reward and save video to drive
eval_episodes: 5
start_time: ???
hydra_base_dir: ""
