defaults:
  - method: iqlearn_online
  - env: cave
  - pretraining: none
  - _self_

exp_name: ''
project_name: ${env.name}
device: ???  # to be specified later
env: ???
method: ???
wandb: ???
training_timeout: ???

max_training_episode_length: 2000

# model attributes
cnn_layers: 12  # max is 17
linear_layer_size: 512
n_observation_frames: 3  # includes current pov
alpha: 1e-1

# lstm
# set layers and hidden size to 0 to disable
lstm_layers: 1
lstm_hidden_size: 512
lstm_segment_length: 10

# data augmentation
inventory_noise: 0.1  # scale of gaussian noise added to inventory
random_translate: true
mirror_augment: false # leave off

cyclic_learning_rate: false

seed: 0
checkpoint_frequency: 2000
eval_frequency: 20000
hydra_base_dir: ""
