defaults:
  - method: iqlearn_online
  - env: pen
  - pretraining: none
  - _self_

exp_name: ''
project_name: ${env.name}
device: ???  # to be specified later
env: ???
method: ???
wandb: ???

# training params
cyclic_learning_rate: true

# model attributes
cnn_layers: 12  # max is 17
linear_layer_size: 512
n_observation_frames: 3  # includes current frame
alpha: 1e-1
decay_alpha: false
final_alpha: 1e-2
termination_confidence_threshhold: 0.15  # for either termination critic or action probability

# lstm
# set layers and hidden size to 0 to disable
lstm_layers: 1
lstm_hidden_size: 512
lstm_segment_length: 10

# data augmentation
normalize_obs: true
inventory_noise: 0.1  # scale of gaussian noise added to inventory
random_translate: true
mirror_augment: false  # leave off

# curriculum learning
curriculum_training: true
initial_curriculum_size: 100
curriculum_refresh_steps: 2000
variable_training_episode_length: true
min_training_episode_length: 500
emphasize_new_samples: false
emphasized_fraction: 0.15
emphasis_relative_sample_frequency: 3
extracurricular_sparsity: 100

# record keeping
seed: 0
checkpoint_frequency: 5000  # save model
save_gifs: true  # save gifs to wandb at checkpoints
eval_frequency: 0  # calc reward and save video to drive
eval_episodes: 5
start_time: ???
hydra_base_dir: ""
