defaults:
  - method: iqlearn_online
  - env: cave
  - pretraining: none
  - _self_

exp_name: ''
project_name: ${env.name}
device: ???  # to be specified later
env: ???
method: ???
wandb: ???

max_training_episode_length: 2000

# model attributes
cnn_layers: 17  # max is 17
linear_layer_size: 1024
n_observation_frames: 6  # includes current pov
alpha: 1e-2

# lstm
# set layers and hidden size to 0 to disable
lstm_layers: 1
lstm_hidden_size: 1024
lstm_segment_length: 10

# data augmentation
inventory_noise: 0.1  # scale of gaussian noise added to inventory
random_translate: true
mirror_augment: false


seed: 0
checkpoint_frequency: 1000
hydra_base_dir: ""
