defaults:
  - method: iqlearn
  - env: cave
  - _self_

exp_name: ''
project_name: ${env.name}
device: ???  # to be specified later


discount_factor: 0.99
n_observation_frames: 3

batch_size: 64
starting_steps: 2000
suppress_snowball_steps: 500
training_steps: 2000
learning_rate: 3e-4
alpha: 1e-3

# for SAC
double_q: false
tau: .05
q_lr: 3e-4
policy_lr: 1e-4

# for curiosity
curiosity_pretraining_steps: 1500
curiosity_lr: 3e-4


algorithm: 'sac'  # curiosity, supervised_learning, online_imitation, sac
loss_function: 'iqlearn'  # iqlearn, sqil

hydra_base_dir: ""

seed: 0
pretrain: null

env: ???
method: ???
wandb: ???
